"""Add display_name and bio to users table

Revision ID: 161b9b692338
Revises: 7828fe4031f5
Create Date: 2025-07-07 13:54:08.292985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '161b9b692338'
down_revision: Union[str, None] = '7828fe4031f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('files', sa.Column('file_url', sa.String(), nullable=True))
    op.alter_column('files', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_files_object_name'), table_name='files')
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.drop_column('files', 'original_filename')
    op.drop_column('files', 'object_name')
    op.drop_column('files', 'size')
    op.drop_column('files', 'bucket_name')
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.add_column('files', sa.Column('bucket_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('object_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.create_index(op.f('ix_files_object_name'), 'files', ['object_name'], unique=True)
    op.alter_column('files', 'upload_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('files', 'file_url')
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###
