"""Add UserPublic and UserDetail schemas, implement audit_log stub, and adjust admin stats endpoint

Revision ID: 33abbe1a6c25
Revises: 562a3833d32e
Create Date: 2025-08-24 14:07:02.178589+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33abbe1a6c25'
down_revision: Union[str, None] = '562a3833d32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
