"""Add display name length limit and fix login password handling

Revision ID: 60a7d5e96bc2
Revises: 87eaee8aa28d
Create Date: 2025-08-31 10:33:29.393541+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a7d5e96bc2'
down_revision: Union[str, None] = '87eaee8aa28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
