"""add end-to-end encryption for passwords with private and public keys, add endpoint for private and public key

Revision ID: 87eaee8aa28d
Revises: a278ee5064f3
Create Date: 2025-08-24 15:21:22.184708+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eaee8aa28d'
down_revision: Union[str, None] = 'a278ee5064f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
