"""Add collections, tracks, and collaborators tables

Revision ID: a61cbabdff5d
Revises: 36a3570455fb
Create Date: 2025-09-24 20:19:05.812253+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61cbabdff5d'
down_revision: Union[str, None] = '36a3570455fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_type', sa.Enum('ALBUM', 'PLAYLIST', 'COMPILATION', name='collectiontype'), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('curator_note', sa.Text(), nullable=True),
    sa.Column('cover_art_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_collaborative', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_collection_type'), 'collections', ['collection_type'], unique=False)
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_table('collection_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id', name='uq_collection_collaborator')
    )
    op.create_index(op.f('ix_collection_collaborators_id'), 'collection_collaborators', ['id'], unique=False)
    op.create_table('collection_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('track_order', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'track_order', name='uq_collection_track_order')
    )
    op.create_index(op.f('ix_collection_tracks_id'), 'collection_tracks', ['id'], unique=False)
    
    # Corrected block to drop the index
    try:
        op.drop_index('ix_audio_files_stored_filename', table_name='audio_files')
    except Exception as e:
        print(f"Could not drop index, it might not exist: {e}")
        pass # Index doesn't exist, continue

    op.alter_column('users', 'max_audio_uploads',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'max_audio_uploads',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.create_unique_constraint(op.f('audio_files_stored_filename_key'), 'audio_files', ['stored_filename'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_collection_tracks_id'), table_name='collection_tracks')
    op.drop_table('collection_tracks')
    op.drop_index(op.f('ix_collection_collaborators_id'), table_name='collection_collaborators')
    op.drop_table('collection_collaborators')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_collection_type'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
