"""add_is_active_column_to_users

Revision ID: f8aa41eceb4c
Revises: 5987f6612605
Create Date: 2025-06-01 14:09:59.267782+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f8aa41eceb4c'
down_revision: Union[str, None] = '5987f6612605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', 
                  sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'))
                 )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###